### ISSUE TITLE
Disable pull to refresh

### ISSUE THREAD

**Issue by dviree** [hemker/apkgrabber#50]
Needs to be an option

**Comment by tjsuominen** [comment]
Don't pull = no refresh :)

**Comment by TPS** [comment]
@tjsuominen I think @dviree means that it's too easy to overscroll the top of the list when there're many updates, which clears & refreshes the list accidentally, so allowing to disable that would solve it.

Another way might be to, on additional updates, _merge_ instead of clearing. (Sometimes, a merge, of a kind, happens anyway, when refreshing @ exactly the wrong moment, which gives mistaken duplication of an update listing [e.g., "APKMirror APKMirror" under 1 app listing], so this _might_ be an opportunity to clean that up, too.)

**Comment by tjsuominen** [comment]
Point understood, yet I haven't seen (m)any apps of such an option. Yes, sometimes one could overscroll, but yet no harm done.
