### ISSUE TITLE
Collaborate with upstream

### ISSUE THREAD

**Issue by Madis0** [hemker/apkgrabber#69]
Heads up, the original APKUpdater has resumed development! Now would be a great time to merge some new features to upstream and possibly collaborate on the original project.

**Comment by m-rey** [comment]
Any update on this?

I guess I'm not the only user that is unsure whether to use APKGrabber or APKUpdater. Joining efforts to work on one combined application might help both and devs.

If that's not possible, maybe regularly porting the features from one project to the other might be an option

What are your thoughts on that?

**Comment by hemker** [comment]
@m-rey @Madis0 I already thought about this question. The best option - at least what I'd prefer - is myself contributing to the original APKUpdater now. The codebase I used must be cleaned and brought into an up-to-date state, including the build system. This is a lot of effort, which can be put on developing new features in the upstream project instead - because the upstream project is modernized and done from scratch. Furthermore, I already contributed with a new feature two weeks ago and I am willing to port  ApkPure as a source. The only thing I'm afraid of is my pull requests not being merged for a long time due to inactivity.
If we can be sure that new features are merged by rumboalla within acceptable time, I'd like to archive my fork.

Dennis

**Comment by m-rey** [comment]
I completely understand.

Would you also be willing to rebase your features to the upstream codebase and offer that as the "new apkgabber" or similar, if upstream goes back to being inactive and thus doesn't merge your PRs?

**Comment by hemker** [comment]
@m-rey I provided a pull request rumboalla/apkupdater#346 for integrating ApkPure as a source. Let's take a look what happens - possibly it's getting merged soon, otherwise I have to think about rebasing ApkGrabber to 2.x branches from the original repo.

**Comment by hemker** [comment]
@m-rey Things work out, I close this issue :)
